### ISSUE TITLE
Eval expression with $c in the variable name throw an exception

### ISSUE THREAD

**Issue by lucasgl** [zzzprojects/Z.Expressions.Eval#139] opened 2022-09-29 19:57 UTC
For example
Expression: "$cookingTimer == 0" 

throw exception: 
"zzz_SOMEGUIDer" expression is null.

**Comment by JonathanMagnan** [comment] 2022-09-30 01:40
Thank you to report this issue.

We will look at this to see if something can be fixed on our side.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment] 2022-09-30 15:08
Hello @lucasgl ,

Do you think you could create a runnable project with the issue? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue. You can send it in private here: info@zzzprojects.com

Unfortunately, we are not able to reproduce this exact problem, we are currently missing something, so having a project that can reproduce it will surely save us some time.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment] 2022-10-05 12:51
Hello again, 

Since our last conversation, we haven't heard from you. 

As mentioned in my previous message, could you create a runnable project with the issue? 

Let me know if you have any questions. 

Best regards, 

Jon

**Comment by lucasgl** [comment] 2022-10-06 12:52
Sorry, got busy in the last days, will get back in it next week! Thanks for
the follow up!

**Comment by JonathanMagnan** [comment] 2022-10-14 14:01
Hello @lucasgl , 

A simple reminder that we are here to assist you. 

Don't hesitate to contact us if you need anything. 

Best regards,

Jon

**Closed as completed** 2022-10-28 13:29 UTC
