### ISSUE TITLE
Null property value causes eval exception

### ISSUE THREAD

**Issue by jefferysun** [zzzprojects/Z.Expressions.Eval#6] opened 2017-05-05 03:49 UTC
Following code works:

`dynamic expandoObject = new ExpandoObject();`
`expandoObject.Property1 = true;`
`if (Eval.Execute<bool>(@"Property1 == true", expandoObject))`
`{`
 `    Console.WriteLine(@"Property1 == true");`
`}`

But the following (with an irrelevant null property) will just error out:

`dynamic expandoObject = new ExpandoObject();`
`expandoObject.Property1 = true;`
**`expandoObject.Property2 = null;`**
`if (Eval.Execute<bool>(@"Property1 == true", expandoObject))`
`{`
`    Console.WriteLine(@"Property1 == true");`
'}`

Is this something you can fix?
Thank you.

**Comment by JonathanMagnan** [comment] 2017-05-05 13:01
Hello @jefferysun ,

That is definitely something we can fix. In fact, we fixed it a few minutes ago in our dev environment.

The issue was caused when trying to get value type from ExpandoObject properties.

We will investigate a little bit more this issue but we expect to release the fix today or during the weekend.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-05-06 19:02
Hello @jefferysun ,

The v2.0.8 has been released:
https://www.nuget.org/packages/Z.Expressions.Eval/2.0.8

Let us know if the issue is fixed on your side.

Best Regards,

Jonathan

**Comment by jefferysun** [comment] 2017-05-06 19:11
This works now.  Thank a lot for such quick turnaround.



-------- Original Message --------

**Comment by JonathanMagnan** [comment] 2017-05-06 19:11
Closing Comment: Fix confirmed

**Closed as completed by JonathanMagnan** 2017-05-06 19:11 UTC
