### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by Alphaquest2005** [zzzprojects/Z.Expressions.Eval#14] opened 2017-10-30 01:11 UTC
When i try to execute the following code i get a 'Object reference not set to an instance of an object.'

```csharp
var evalContext = new EvalContext();
evalContext.RegisterDomainAssemblies();
var body = @" new DomainMessage(""UserValidated"",cp?.Messages[""ValidatedUser""]?.Entity,
                                new StateEventInfo(cp?.Actor?.Process?.Id, 
Context.Domain.Events.DomainEventPublished),
                                cp.Actor.Process, cp.Actor.Source)";
var res = evalContext.Compile<Func<IComplexEventParameters, IProcessSystemMessage>>(body, "cp");
```

The parameter contains dynamic types is that the cause?

**Comment by JonathanMagnan** [comment] 2017-10-30 14:29
Hello @Alphaquest2005,

Yes, this could be the cause since your expression is complex.

We support dynamic types but they may have case that we might have forgotten.

Do you think you could send us a full example that doesn't work to make sure on our side we try to fix the right issue?

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-11-27 02:13
Hello @Alphaquest2005 ,

Do you think you will be able to find time to provide us an example?

In your current example, I'm not sure which field or property is currently dynamic types or real types.

Best Regards,

Jonathan

**Comment by Alphaquest2005** [comment] 2017-11-27 02:15
Hi thank for following up…
Fact is I just refactored out the dynamic type and replaced it with dictionary… to match the rest of static c#....
So far so good…

Thanks any ways

joseph

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by JonathanMagnan** [comment] 2017-12-13 19:50
Hello @Alphaquest2005 ,

We will close this issue seem there is no so much we can do currently since you look to have fixed it on your side.

Feel free to reopen if I shouldn't have closed it.

Best Regards,

Jonathan

**Closed as completed by JonathanMagnan** 2017-12-13 19:50 UTC
