### ISSUE TITLE
Seems that // comments cause trouble

### ISSUE THREAD

**Issue by daveyostcom** [zzzprojects/Z.Expressions.Eval#53] opened 2019-03-21 05:22 UTC
Please see line 50 in [this example](https://dotnetfiddle.net/ZE67wT).

**Comment by JonathanMagnan** [comment] 2019-03-21 09:56
Hello @daveyostcom ,

Thank you for reporting.

We will look at it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2019-03-21 10:34
Hello @daveyostcom ,

Did you success to reproduce this issue outside of Fiddle?

That issue is caused by Fiddle that uses only "\n" instead of "\r\n" for new line. A simple string.split doesn't work either: https://dotnetfiddle.net/eoHJ2q

```csharp
var text = @"
// Take out this comment, and it works. Leave it in and the output is a blank line.
X + Y";

var lines = text.Split(new string[] { Environment.NewLine }, StringSplitOptions.None);
Console.Write(lines.Count()); // 1 in Fiddle, 3 in Visual Studio
```

Since we are the co-owner of Fiddle, I guess the issue is still on our side ;)

We will look at it and try to deploy a new version of Fiddle with this fix in 2 weeks.

**Comment by daveyostcom** [comment] 2019-03-21 11:05
Happens in Rider on Mac.

**Comment by JonathanMagnan** [comment] 2019-03-21 12:15
Oh damn, you are right.

The end line is not the same in every `OS`. So I guess we will need to fix both.

Fiddle and C# Eval

**Comment by JonathanMagnan** [comment] 2019-03-21 14:59
Hello @daveyostcom ,

A new version is now available.

Your Fiddle is now working as expected: https://dotnetfiddle.net/ZE67wT

The issue has been fixed only in the C# Eval Expression, a fix for Fiddle will be provided on the next released.

**Closed as completed** 2019-03-24 15:15 UTC
